## by PeladoNerd https://youtu.be/eoFxMaeB9H4

version: '3.1'

services:

  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8000:80
    env_file: .env  
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    links:
      - mysql:mysql
    volumes:
      - ./wordpress_persistente:/var/www/html


  mysql:
    image: mysql:8.0.13
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql